---
title: "heatwaveR"
output: html_document
date: "2024-01-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Multi-scale Ultra-high Resolution (MUR) SST Analysis fv04.1, Global, 0.01°, 2002-present, Daily
  
```{r, cache=TRUE}
library(dplyr)
library(purrr)
library(ggplot2)
library(heatwaveR)

```

```{r eval=FALSE, cache=TRUE, include=TRUE}


maldives_MUR_heatwaves <- extract_ocean_data(dataset="jplMURSST41[analysed_sst]",
                                             space = c(70, 72, 1, 2), 
                                             time = c("2002-01-01", "2024-01-01")) 



```


```{r}

trial <- maldives_MUR_heatwaves$data |> 
  filter(longitude==70.05) |> 
  filter(latitude==1.05) |> 
  mutate(date=as.Date(time))

ts <- ts2clm(trial, x=date, y=sstAnom, climatologyPeriod = c("2002-06-01", "2024-01-01"))
mhw <- detect_event(ts, x=date, y=seas)

event_line(mhw, x=date, y=sstAnom, spread = 180, metric = intensity_max, 
           start_date = "2002-06-01", end_date = "2024-01-01")

```
