---
title: "Maldives - maximum wave height"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Interactive maps of maximum waveheight (WWW) from from the WAVEWATCH III model 

```{r, warning=FALSE, message=FALSE, fig.width=8, fig.height=12}
library(terra)
library(tidyverse)

ocean_waves <- rast("/Users/rof011/rOceanData/data/maldives/WW3.maximum.hs.tiff")

library(leaflet)

num_colors <- 10  # Adjust the number of colors for granularity
spectral_palette <- colorNumeric(palette = "Spectral", reverse=TRUE, domain = values(ocean_waves), na.color="transparent")

# Leaflet Map with Raster Layer

# Leaflet Map with Raster Layer
leaflet() %>%
  addTiles() %>%
  setView(lat = 4.5, lng = 73.5, zoom = 8) %>%
  addProviderTiles('Esri.WorldImagery', group = "Base Map", options=providerTileOptions(maxNativeZoom=18,maxZoom=100)) |>
  addRasterImage(ocean_waves,  colors = spectral_palette, opacity = 0.8) %>%
  addLegend(pal = spectral_palette, values = values(ocean_waves),  opacity = 0.8) |> 
  addLayersControl(
    baseGroups = c("Base Map"),
    overlayGroups = c("ocean_waves"),
    options = layersControlOptions(collapsed = FALSE)
  )
```
