---
title: "Maldives - marine heatwave variability"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Interactive maps of marine heatwave variability (1981-present) from OAA 1/4° Daily Optimum Interpolation Sea Surface Temperature (OISST).

```{r, warning=FALSE, message=FALSE, fig.width=9, fig.height=15}
library(terra)
library(tidyverse)

mhw_intensity <- rast("/Users/rof011/rOceanData/data/maldives/Bleaching-mhw_annual-mean_variability.tiff")

library(leaflet)

num_colors <- 10  # Adjust the number of colors for granularity
rdbu_palette <- colorNumeric(palette = "Spectral", domain = values(mhw_intensity), n = num_colors)

# Leaflet Map with Raster Layer
leaflet() %>%
  addTiles() %>%
  setView(lat = 3.9, lng = 73.5, zoom = 8) %>%
  addProviderTiles('Esri.WorldImagery', group = "Base Map", options=providerTileOptions(maxNativeZoom=18,maxZoom=100)) |>
  addRasterImage(mhw_intensity,group = "SST", colors = rdbu_palette, opacity = 0.8) %>%
  addLegend(pal = rdbu_palette, values = values(mhw_intensity), title = "Marine heatwave variability", opacity = 0.8) |> 
  addLayersControl(
    baseGroups = c("Base Map"),
    overlayGroups = c("SST"),
    options = layersControlOptions(collapsed = FALSE)
  )



```
